### ISSUE TITLE
unsupported operand type(s) for |: 'ABCMeta' and 'type'

### ISSUE THREAD

**Issue by wangruichen100** [SouradiptoC/CodonU#1]
I can't from CodonU import correspondence_analysis as ca

**Comment by SouradiptoC** [comment]
Please mail me your error tree and the script you were working on while you faced the problem

**Comment by wangruichen100** [comment]
Ok, I have  sent the email.

**Comment by SouradiptoC** [comment]
Upgrade to python 3.10
