### ISSUE TITLE
Unable to import CodonU.analyzer

### ISSUE THREAD

**Issue by laxeye** [SouradiptoC/CodonU#2]
`from CodonU import analyzer as an`

leads to

ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 from CodonU import analyzer as an

File ~/conda/lib/python3.10/site-packages/CodonU/analyzer/__init__.py:1
----> 1 from .cai_comp import calculate_cai
      2 from .rscu_comp import calculate_rscu
      3 from .cbi_comp import calculate_cbi

File ~/conda/lib/python3.10/site-packages/CodonU/analyzer/cai_comp.py:1
----> 1 from cai2 import CAI
      2 from warnings import filterwarnings
      3 from Bio.Data.CodonTable import unambiguous_dna_by_id

ModuleNotFoundError: No module named 'cai2'

Python 3.10.11
CodonU 1.0.4

**Comment by SouradiptoC** [comment]
I am working on some improvements and soon an updated version will be released. Till then, you can manually install cai2 package from pypi. The package should work fine

**Comment by SouradiptoC** [comment]
The new update is now available. The issue will not occur now @laxeye.
