### ISSUE TITLE
Error In Installing CodonU

### ISSUE THREAD

**Issue by abdulmajeedkhatttak1** [SouradiptoC/CodonU#3]
hello i am trying to install CodonU (pip install CodonU) package for my project. I have tried my best to install but i am facing error while installing CodonU. moreover i had tried to sort out this error but i can't. i have attached a screenshot of error that I am facing.
waiting for a nice positive response.
regards Abdul Majeed 
<img width="757" alt="Error_CodonU" src="https://github.com/SouradiptoC/CodonU/assets/87596374/134b07df-d0c0-461e-963a-e62cb357bb55">

**Comment by SouradiptoC** [comment]
CodonU was designed in python 3.11 and has not been updated for newer versions. Try installing it in python 3.11

**Comment by SouradiptoC** [comment]
Hey @abdulmajeedkhatttak1, had it worked?

**Comment by abdulmajeedkhatttak1** [comment]
> CodonU was designed in python 3.11 and has not been updated for newer versions. Try installing it in python 3.11

thanks for giving me the right suggestion on the perfect time. its 100% functional and accurate in python 3.11. CodonU is excellent. boom

**Comment by abdulmajeedkhatttak1** [comment]
> Hey @abdulmajeedkhatttak1, had it worked?

yeah 100% its worked.
