### ISSUE TITLE
All MCA Plotting functions not working. 

### ISSUE THREAD

**Issue by raw937** [SouradiptoC/CodonU#5]
command: viz.plot_mca_aa_aroma(in_file, 11) 
error: AttributeError: module 'CodonU.vizualizer' has no attribute 'plot_mca_aa_aroma'

command: viz.plot_mca_aa_gravy(in_file, 11)
error: AttributeError: module 'CodonU.vizualizer' has no attribute 'plot_mca_aa_gravy'

Same for: 
viz.plot_mca_rscu(in_file, 11)
viz.plot_mca_codon_freq(in_file, 11)

**Comment by SouradiptoC** [comment]
plot_mca_* functions calculated multiple correspondence analysis, but generally only correspondence analysis is necessary. So plot_mca_* functions were changed by plot_ca_* functions. Please look into "Correspondence Analysis Plot" in examples. Can you please also share where you have found the reference of plot_mca_* functions? Somehow, I guess, that document isn't up to date.

**Comment by raw937** [comment]
This doesn't work either viz.plot_ca -> module 'CodonU.vizualizer' has no attribute 'plot_ca_codon_freq' please advise

**Comment by SouradiptoC** [comment]
`plot_ca_*` functions have a slightly different call. Let's say you want to have a plot of codon frequency of compared with respect to codons. Then the function will be `plot_ca_codon_freq_codon()`. If you are interested to compare several genes based of frequency of codons in them, the function will be `plot_ca_codon_freq_gene()`. You can find usage of all the plot function in [Examples/5_Vizualization](https://github.com/SouradiptoC/CodonU/blob/master/Examples/5_Vizualization.ipynb)

**Comment by raw937** [comment]
You have functions listed in the tutorial that don't work. I am trying to recreate these plots from the examples/5_Vizualization. 

These are the commands which have errors and the example it's to be updated if the mca function isn't present. 

These commands in this tutorial all have AttributeErrors because none of these functions are present I guess. 
viz.plot_mca_codon_freq(in_file, 11)
viz.plot_mca_aa_gravy(in_file, 11)
viz.plot_mca_rscu(in_file, 11)
viz.plot_mca_codon_freq(in_file, 11)
-> errors!

These functions are not in examples/5_Vizualization link!

Would these be the correct commands?
viz.plot_ca_codon_freq_codon(in_file, 11)
viz.plot_ca_codon_freq_gene(in_file, 11)
Or
plot_ca_codon_freq_codon(in_file, 11)
plot_ca_codon_freq_gene(in_file, 11)

Neither of these are found in the examples. 

Also, for msa_rcsu and the other functions would are the commands? 

These don't work:
viz.plot_mca_codon_freq(in_file, 11)
viz.plot_mca_aa_gravy(in_file, 11)
viz.plot_mca_rscu(in_file, 11)

**Comment by SouradiptoC** [comment]
I'll look into the example file, and let you know when updated.

**Comment by Hasanzahid10** [comment]
# how too solve this problem, pls help me
when I am run this code 
viz.plot_mca_rscu(in_file, 11)
biopython file show this message 
AttributeError: 'FastaIterator' object has no attribute 'read'

**Comment by SouradiptoC** [comment]
In the previous version (prior to sep 2023) `plot_mca_*` functions were used. But in the current version `plot_ca_*` functions are being used. Example files don't put a clear line between this. If you are using CodonU version release after sep 2023, skip the `plot_mca_*` funcs. Go with updated `plot_ca_*` funcs. @Hasanzahid10

**Comment by Hasanzahid10** [comment]
> In the previous version (prior to sep 2023) `plot_mca_*` functions were used. But in the current version `plot_ca_*` functions are being used. Example files don't put a clear line between this. If you are using CodonU version release after sep 2023, skip the `plot_mca_*` funcs. Go with updated `plot_ca_*` funcs. @Hasanzahid10

Thank you so much

**Comment by Hasanzahid10** [comment]
I am use this
viz.plot_phy_fas(in_file)  but this file show me 
ValueError: Sequences must all be the same length
how to solve it pls tell me

**Comment by SouradiptoC** [comment]
Please create a seperate issue and mention details of what were you trying so that i can recreate the issue.
