### ISSUE TITLE
I have query about cai2

### ISSUE THREAD

**Issue by bony446** [SouradiptoC/CodonU#6]
![image](https://github.com/SouradiptoC/CodonU/assets/92576096/13cd9e52-b81a-4063-9948-9f5f53d74672)

ModuleNotFoundError: No module named 'cai2'

**Comment by SouradiptoC** [comment]
I believe you are using an older version of CodonU. The recent one is 1.1.2. Can you once check the version of CodonU you are using.

**Comment by SouradiptoC** [comment]
Hey @bony446 , is the issue resolved?

**Comment by MsAlEhR** [comment]
Hey @SouradiptoC ,

I have multiple  questions regarding the CAI (Codon Adaptation Index) calculator function.
 How do we derive CAI for just one gene? I just have one gene sequence; how can I define a reference sequence for that gene in  an.calculate_cai()? Is there a way with your tool to calculate CAI for each gene with a global index?
 
 Thanks

**Comment by SouradiptoC** [comment]
You can do it. See `calculate_cai` is a high level function calling several other functions in it. Inside it, it calls to `cai` function ([line no 240 ](https://github.com/SouradiptoC/CodonU/blob/9a135a3902aaac91762824b676af5c10636f155e/CodonU/analyzer/internal_comp.py#L240)of analyzer/internal_comp).  This function takes the seq we want to calculate CAI of and reference sequence(s) for it. Just look into the function and you will understand.

P.S. 
 * As this `cai` is an internal function, if you want to import it, you should go like 
 ```
 from CodonU.analyzer.internal_comp import cai
```
* `references` in the function call takes a list. But if you only want to pass a single seq, pass it inside a list.

**Comment by MsAlEhR** [comment]
Thank you for your answer!

I tried your suggestion, but I got an error. It seems like we can't import from the internal function in the current version of the code.

I've found a workaround for my work, but I wanted to let you know about this potential bug in case you want to fix it.

Here's the error message I received:
`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[42], line 1
----> 1 from CodonU.analyzer.internal_comp import cai

ImportError: cannot import name 'cai' from 'CodonU.analyzer.internal_comp' `

**Comment by SouradiptoC** [comment]
Thanks for bringing this to my knowledge. But i guess by the time of execution of that line, you already had the name `cai`. If `calculate_cai` is working in your code, then there is no issue from the side of CodonU (as `calculate_cai` calls `cai`, see [here](https://github.com/SouradiptoC/CodonU/blob/9a135a3902aaac91762824b676af5c10636f155e/CodonU/analyzer/cai_comp.py#L4)). Other wise there may be a circular dependency going on. Try once more 
```
from CodonU.analyzer.internal_comp import cai
```
With it being the first execution of the notebook. Let me know the results

**Comment by MsAlEhR** [comment]
Here is the first execution 
![xx](https://github.com/SouradiptoC/CodonU/assets/11368704/11d7bb2d-c3e3-4c9a-a287-036235ff893d)

**Comment by SouradiptoC** [comment]
Ok, i'll look into it
