### ISSUE TITLE
Not identical Output 

### ISSUE THREAD

**Issue by SouradiptoC** [SouradiptoC/CodonU#7]
Hello sir, 
I am new user CodonU .I have one question about output.
I am run Staphylococcus_aureus.fasta file but my output not to same your output.
why.. if  you want I  will share my output screenshot  ............

_Originally posted by @Hasanzahid10 in https://github.com/SouradiptoC/CodonU/issues/4#issuecomment-2118682022_

**Comment by SouradiptoC** [comment]
What are the differences?

**Comment by Hasanzahid10** [comment]
Hello sir.  At first sorry  to disturbing  you.
First one my output file screenshot
Second  one your output screenshot.
This is the different.....

**Comment by SouradiptoC** [comment]
I can't see any screenshot, can ou check once?

**Comment by Hasanzahid10** [comment]
Now Check  this sir

**Comment by SouradiptoC** [comment]
Still don't mate. Try commenting directly in github, rather than sending from mail.
